name: Making better websites | Adoro Media
markdown: redcarpet
highlighter: pygments
permalink: /articles/:title/
url: https://adoromedia.com
include: ['_pages']
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]